changed VoxelToDistFunc.cpp to include Initialize_Geometry class.  Getting an error about undefined reference to vtable for mfem::BackwardEulerSolver  Need to troubleshoot that.  Also need to add Discontinuous Galerkin to Initialize_Geometry class